### ISSUE TITLE
Make lsh_exec.sh compatible with crontab

### ISSUE THREAD

**Issue by tomaswest** [ibz/lightning-shell#13]
If you try to run lsh_exec.sh from crontab, it will fail, because it is not compatible with "-it" flag for docker exec command.
More info about this here https://stackoverflow.com/questions/37089033/docker-exec-is-not-working-in-cron
Not a big problem for me - I've just made my own lsh_exec_crontab.sh for such case, without "-it" flag.
I am not a big of code writer, but it should be possible to make lsh_exec.sh detect whether it is executed from shell, or from cron table.

**Comment by ibz** [comment]
Added `lsh_exec_ni.sh` in [v0.1.10](https://lightningshell.app/history/#v0.1.10)
