### ISSUE TITLE
Referencing config file from shell via Umbrel cron job 

### ISSUE THREAD

**Issue by mcsnubbs** [ibz/lightning-shell#14]
I've successfully used charge-lnd via lightning shell which is installed in my Umbrel node.
Within lightning shell, the config file is placed in /data/charge-lnd.config.

I've attempted to set up a cron job to run charge-lnd every 5 minutes with the following cron entry someone posted:

*/5 * * * * (docker exec -u lnshell -w /home/lnshell lightning-shell_web_1 /home/lnshell/.local/bin/charge-lnd --config /mnt/data/umbrel/app-data/lightning-shell/data/charge-lnd.config) 2>&1 | logger -t charge-lnd

However, when I check the syslog, it's giving me an error that the "config file not found." Im assuming that this has to do with my path to the config and have attempted a variety of options/paths to find the file with charge-lnd.

I assume this is rather simple for someone familiar with Docker / Lightning Shell on Umbrel. Any help greatly appreciated.

**Comment by ibz** [comment]
`/mnt/data/umbrel/app-data/lightning-shell/data/charge-lnd.config` is `/data/charge-lnd.config` under Lightning Shell.
