### ISSUE TITLE
Lntop

### ISSUE THREAD

**Issue by Stefan14K** [ibz/lightning-shell#7]
Is there a way to run lntop in the backround that i can turn off my pc?

**Comment by ibz** [comment]
Sure, here are the steps:

1. run `screen`
2. now that you are inside `screen`, run `lntop`
3. detach screen with `Ctrl-A D`, that is `Ctrl-A`, followed by `D`
   * you should see a message that `screen` is now detached
4. when you come back to Lightning Shell later, run `screen -dr` to attach your old session (it may ask you *which one* you want if you have more than one detached)

PS: you can have more than one "window" inside the same `screen`! Use `Ctrl-A C` to create a new window, `Ctrl-A W` to list windows and `Ctrl-A 0` `Ctrl-A 1` `Ctrl-A 2`... to switch to window 0, 1, 2...

**Comment by Stefan14K** [comment]
Thanks man it works. Where can I send you some sats?

**Comment by ibz** [comment]
@Stefan14K thanks, I looked into setting up my node for accepting sats, but apparently it's a bit harder than I thought - I need to expose BTC Pay Server to the outside through nginx, I guess. I'll get to it eventually, it's just not top priority.
Thanks for the thought though.
I'll leave this issue open until I get around to do it.

**Comment by ibz** [comment]
Done. You can type "about" in the version last released and find out. Thanks. :)
