### ISSUE TITLE
More igniter.conf documentation

### ISSUE THREAD

**Issue by RooSoft** [ibz/lightning-shell#8]
Could be a nice touch to explain in which folder that file should be created... maybe also point to some documentation such as the original repository, maybe, to avoid having to keep it up to date.

```bash
$ igniter
Please edit igniter.conf and set your own route
```

**Comment by ibz** [comment]
Will do.

In general, documentation is not great so far. Would be nice if every app came with a man page, but very few do.

In particular, I'll take care of this case. Thanks for bringing it up!

**Comment by maxmerlin78** [comment]
How do you execute igniter in the LN Shell? I have adapted the igniter.conf, the command ./igniter.sh build or send

**Comment by ibz** [comment]
Do `cat ~/.local/bin/igniter`. This is the script that checks the config and executes `igniter`.
